Add test script for prow test jobs
metal3-io/hardware-classification-controller pull request #10
Opened 2020-05-06 16:11 UTC by digambar15

Added gofmt, govet, markdownlint, shellcheck, unit shell scripts

2020-05-07 13:55 UTC, dhellmann requested changes

2020-05-07 13:55 UTC, dhellmann commented on hack/gofmt.sh
> +  if [ -n "$(gofmt -l "${TOP_DIR}/pkg" "${TOP_DIR}/cmd")" ]; then
The paths being passed to gofmt here and on the next line need to reflect the location of the source code in this repository. It looks like you want api and controllers instead of pkg and cmd.

2020-05-07 13:55 UTC, dhellmann commented on hack/govet.sh
> +  go vet "${TOP_DIR}"/pkg/... "${TOP_DIR}"/cmd/...
Same comment about source paths.

2020-05-07 13:55 UTC, dhellmann commented on hack/unit.sh
> +  go test -v ./pkg/... ./cmd/... -coverprofile "${ARTIFACTS}"/cover.out
Same comment about source paths.

2020-05-07 14:13 UTC, digambar15 commented on hack/gofmt.sh
> +  if [ -n "$(gofmt -l "${TOP_DIR}/pkg" "${TOP_DIR}/cmd")" ]; then
Yes, I will replace it to API and controller

2020-05-08 10:01 UTC, digambar15 commented on hack/govet.sh
> +  go vet "${TOP_DIR}"/pkg/... "${TOP_DIR}"/cmd/...
Done!

2020-05-08 10:01 UTC, digambar15 commented on hack/unit.sh
> +  go test -v ./pkg/... ./cmd/... -coverprofile "${ARTIFACTS}"/cover.out
Done!

2020-05-08 10:01 UTC, digambar15 commented on hack/gofmt.sh
> +  if [ -n "$(gofmt -l "${TOP_DIR}/pkg" "${TOP_DIR}/cmd")" ]; then
Done!

2020-05-13 14:31 UTC, dhellmann commented on hack/gofmt.sh
> +  if [ -n "$(gofmt -l "${TOP_DIR}/pkg" "${TOP_DIR}/cmd")" ]; then
You will need to change line 12 as well, so the sets of paths match in both calls to gofmt.

2020-05-13 14:51 UTC, dhellmann approved these changes
/lgtm

2020-05-13 14:53 UTC, merged