Fixed Bugs #31 #32 #33
metal3-io/hardware-classification-controller pull request #34
Opened 2020-08-12 13:18 UTC by ravipwaghmare

Fixed Following Bugs:
https://github.com/metal3-io/hardware-classification-controller/issues/31
https://github.com/metal3-io/hardware-classification-controller/issues/32
https://github.com/metal3-io/hardware-classification-controller/issues/33

@maelk @digambar15  
Kindly Review.

2020-08-12 15:09 UTC, maelk commented
/ok-to-test

2020-08-12 15:10 UTC, maelk reviewed
looks good to me

2020-08-13 05:42 UTC, digambar15 requested changes

2020-08-13 05:42 UTC, digambar15 commented on controllers/hardwareclassification_controller.go
> +	hccLog := hcReconciler.Log.WithName(HWControllerName).WithValues("metal3-hardwareclassification", req.NamespacedName)
change it to hwclog

2020-08-13 05:55 UTC, ravipwaghmare commented on controllers/hardwareclassification_controller.go
> +	hccLog := hcReconciler.Log.WithName(HWControllerName).WithValues("metal3-hardwareclassification", req.NamespacedName)
Done

2020-08-13 06:41 UTC, digambar15 commented
Looks good.

2020-08-13 06:56 UTC, digambar15 approved these changes

2020-08-13 08:52 UTC, merged