This Patch fixes issue #36
metal3-io/hardware-classification-controller pull request #37
Opened 2020-08-17 09:34 UTC by sharajat

Fix for the issue
#36 

@maelk @digambar15 
Kindly review.

2020-08-17 12:57 UTC, dhellmann requested changes
Could you provide a more descriptive commit message so that someone looking at the file history does not have to go to GitHub to learn what #36 was about?

2020-08-17 13:00 UTC, sharajat commented
yes sure, will do that.

2020-08-18 09:59 UTC, digambar15 approved these changes
Looks good.

2020-08-20 05:34 UTC, digambar15 commented
I need to merge this PR as QA team is waiting for this fix. Thanks!

2020-08-20 05:37 UTC, merged