Updated readme.md
metal3-io/hardware-classification-controller pull request #44
Opened 2020-09-08 09:26 UTC by nehaalhat

1. Updated readme.md
2. Removed configuration.md.

2020-09-08 09:35 UTC, maelk reviewed
does this PR miss the dev-setupd.md docs that was moved out of the Readme ?

2020-09-08 09:42 UTC, nehaalhat commented
We have already raised PR for dev-setup.md under docs and it is merged, so removed those  steps from readme.md and added dev-setup.md reference under resources.

2020-09-14 04:38 UTC, digambar15 commented
Looks good!

2020-09-14 04:50 UTC, digambar15 requested changes
Please work on comments

2020-09-14 04:50 UTC, digambar15 commented on README.md
I would like to mention the goal of HWCC, what you mentioned below is more of implementation details. First elaborate what's goal of the project then you can keep below "how" part as is.

2020-09-14 14:27 UTC, digambar15 approved these changes
Looks good

2020-09-15 05:09 UTC, merged