Adding Rule book for Disk and NIC selection.
metal3-io/hardware-classification-controller pull request #69
Opened 2021-04-02 12:28 UTC by Ashughorla

Added document for rules which will be used by user for Disk and NIC selection.
Related to [Proposal](https://github.com/metal3-io/metal3-docs/pull/152)

Kindly review.
@dhellmann @digambar15 @maelk @zaneb @russellb

2021-04-05 13:51 UTC, jtwill98 reviewed
Please add broadcom.

2021-04-08 11:10 UTC, fmuyassarov commented
/ok-to-test

2021-04-08 15:13 UTC, Ashughorla commented
/retest

2021-04-08 15:17 UTC, Ashughorla commented
> Please add broadcom.

Addressed

2021-05-19 13:23 UTC, digambar15 requested changes
Numbering of section contents should be fixed.

2021-05-19 13:23 UTC, digambar15 commented on docs/rule_book.md
> +  1. SCSI adapter number `host`
Fix numbering

2021-05-19 13:23 UTC, digambar15 commented on docs/rule_book.md
> +  1. SCSI adapter number `host`
all lines represent 1

2021-05-19 13:23 UTC, digambar15 commented on docs/rule_book.md
> +  flag as True.
Same here! Fix numbering

2021-05-19 13:23 UTC, digambar15 commented on docs/rule_book.md
> +  1. NVMe : No `hctl` Pattern, rotational flag as False and model name
Ditto!

2021-05-19 13:23 UTC, digambar15 commented on docs/rule_book.md
> +  1. Broadcom NIC Vendor ID is 0x14e4.
Ditto!

2021-05-20 19:32 UTC, zaneb commented on docs/rule_book.md
> +  1. SCSI adapter number `host`
This is the normal way to do it in markdown. It renders as an ordered list in HTML, so the output numbering is always correct: https://github.com/metal3-io/hardware-classification-controller/pull/69/files?short_path=e0c0f2a#diff-e0c0f2a9ad43f0f94a2de56bb81a793415c04a2169f769eb9b5222333bd35c54

2021-05-27 08:06 UTC, Ashughorla commented on docs/rule_book.md
> +  1. SCSI adapter number `host`
Yes, numbering will look like that in .md file.

2021-06-14 13:27 UTC, digambar15 approved these changes
Looks good

2021-06-21 09:12 UTC, merged